#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ! getent hosts $DSCV; then
  echo "=== Cannot resolve the DNS entry for $DSCV. Has the service been created yet, and is SkyDNS functional?"
  echo "=== See http://kubernetes.io/v1.1/docs/admin/dns.html for more details on DNS integration."
  echo "=== Sleeping 10s before pod exit."
  sleep 10
  exit 0
fi

. /start-common.sh

service ssh start

MASTER=$(getent hosts $DSCV | awk -F ' ' '{print $1}')
echo "$(date) - $0 - master ip: $MASTER"
#/opt/auto-cp-ssh-id.sh root $PASSWD $MASTER

HADOOP_HOME=/opt/hadoop

sed -i "s/hadoop-master/$MASTER/" $HADOOP_HOME/etc/hadoop/core-site.xml
sed -i "s/hadoop-master/$MASTER/" $HADOOP_HOME/etc/hadoop/yarn-site.xml

$HADOOP_HOME/bin/hdfs --daemon start datanode
$HADOOP_HOME/bin/yarn --daemon start nodemanager

tail -f $HADOOP_HOME/logs/*
